account/urls.py
from django.urls import path
from .views import *
app_name='account'

urlpatterns = [
    path('register/',register_view,name='register'),
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from users.views import *
urlpatterns = [
    path('',home_view,name='home'),
    path('account/',include('account.urls')),
    path('about/',about__view,name='about'),
    path('contact/',contact__view,name='contact'),
    path("admin/", admin.site.urls),
]

account/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Users(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name=models.CharField(max_length=150)
    surname=models.CharField(max_length=150)
    work=models.CharField(max_length=150)
    about=models.TextField()
    create_time=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.name} {self.surname} | {self.author}"

account/forms.py
from django import forms

class RegisterForm(forms.Form):
    username=forms.CharField(max_length=30,label='Username')
    password=forms.CharField(max_length=10,label='Password',widget=forms.PasswordInput)
    confirm=forms.CharField(max_length=10,label='Password confirm',widget=forms.PasswordInput)

def clean(self):
    username=self.clean_data['username']
    password=self.clean_data['password']
    confirm=self.clean_data['confirm']
        
    if password and confirm and password != confirm:
        raise forms.ValidationError('Shifre eyni deyil  . ')
    values={
        'username':username,
        'password':password
    }
    return values

class LoginForm(forms.Form):
    username=forms.CharField(max_length=30,label='Username')
    password=forms.CharField(max_length=10,label='Password')

account/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

def register_view(request):
    form = RegisterForm(request.POST or None)
    
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        newUser = User(username=username)
        newUser.set_password(password)
        
        newUser.save()
        login(request, newUser)
        
        return redirect('home')
    context = {
        'form': form,
    }
    return render(request, 'register.html', context)

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = LoginForm(request=request)
    
    context = {
        'form': form,
    }
    return render(request, 'login.html', context)


def logout_view(request):
    logout(request)
    return redirect('home')

users/views.py
from django.shortcuts import render
from .models import Users
# Create your views here.

def home_view(request):
    users=Users.objects.all()
    return render(request,'index.html',{'users':users})

def about__view(request):
    return render(request,'about.html')

def contact__view(request):
    return render(request,'contact.html')

templates/about.html
{% extends "base.html" %}
{% block title%}
    <title>About Page</title>
{% endblock title%}

{%block body%}
    <h2>About Html</h2>
{%endblock body%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}    
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block title %}
    <title>Home Page</title>
    {% endblock title %}
</head>
<body>
    <div class="navbar">
        <div class="img">
            <i class="fa-brands fa-wolf-pack-battalion"></i>
            <div class="legend">Legends.net</div>
        </div>
        
        <div class="nav_links">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                {% if user.is_authenticated %}
                    
                    <li><a href="{% url 'account:logout' %}" title="logout"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                {% else %}
                    <li><a href="{% url 'account:register' %}">Register</a></li>
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    
    <div class="container">
        {% block body %}
        {% endblock body %}
    </div>
    <div class="message-box" id="messageBox"></div>
    <script src="{% static 'main.js' %}"></script> 
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block title%}
    <title>Contact Page</title>
{% endblock title%}

{%block body %}
    <p>Contact Html</p>
{%endblock body %}

templates/index.html
{% extends "base.html" %}
{% block title%}
    <title>Home Page</title>
{% endblock title%}

{% block body%}
    
    <div class="users">
    <ol>
        <h1 class="user">
            Xoşgəldin  
            {% if user.is_authenticated %}
                {{ user.username }}
            {% else %}
                User
            {% endif %}
        </h1>
        {%for user in users%}
        <li class="write">
            <h3>Müəllif : {{user.author}}</h3>
            <h4>{{user.name}} {{user.surname}}</h4>
            <p>Work : {{user.work}}</p>
            <p>About : {{user.about}}</p>
            <small>Added time :{{user.create_time}}</small>
        </li>
        {% endfor%}
    </ol>
</div>
{% endblock body%}

templates/login.html
{% extends "base.html" %}
{% block title%}
    <title>Login Page</title>
{% endblock title%}

{%block body %}
    <h2>Login Html</h2>
    <form method="post">
        {% csrf_token%}
        {{form.as_p}}
        <button type="submit" class="btn">Daxil ol </button>
    </form>
{%endblock body %}

templates/register.html
{% extends "base.html" %}
{% block title%}
    <title>Register Page</title>
{% endblock title%}

{% block body %}
    <h2 >Register Html</h2>
    <form method="post">
        {% csrf_token%}
        {{form.as_p}}
        <button  type="submit" class="btn">Qeydiyyatdan Kec</button>
    </form>
{% endblock body %}